blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ æé—®æˆ–è®¨è®º (Question or Discussion)
    url: https://github.com/jiangbkvir/jinianbi/discussions/new
    about: è¯·ä½¿ç”¨ GitHub Discussions è¿›è¡Œæé—®æˆ–å‘èµ·è®¨è®ºã€‚
